<a href="https://colab.research.google.com/github/VivianeCorreia/Tech-Challenge/blob/main/Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$ \alpha + \beta =  10 $$

$$ \pmatrix{}
$$

In [22]:
import numpy as np
import scipy as sc
import sympy as sy

In [23]:
#escalar- número (tensor de ordem zero)
#vetor tensor de ordem 1
#matriz
x=2
x2 = np.array([1,2,3])        #vetor com três elementos escalares
x3 = np.array([[1],[2],[3]])  #matriz comtrês elementos vetores com elementos escalares
x4 = np.array([[1,2,3],[1,2,3],[1,2,3]]) # matriz tradicional

In [24]:
print(x2)
print()
print(x3)
print()
print(x4)

[1 2 3]

[[1]
 [2]
 [3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
#dataframe - é uma estrutura tabular

In [26]:
import pandas as pd

In [27]:
lista = np.array([1,2,3,4,5])

df= pd.DataFrame({'coluna': lista, 'coluna 2': lista})

In [28]:
type(df)

pandas.core.frame.DataFrame

In [29]:
df

coluna  coluna 2
0       1         1
1       2         2
2       3         3
3       4         4
4       5         5

In [30]:
df['coluna']

0    1
1    2
2    3
3    4
4    5
Name: coluna, dtype: int64

In [31]:
type(df.coluna)

pandas.core.series.Series

In [33]:
lista[-1]

5